title: Sebastian Bahr # your name (or website title) here
logo: "/images/Sebastian Bahr Foto.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. student in sociology and data scientist with 3 years of commercial experience in a tech startup.
  <br><br>
  Passionated about computational social science and applying machine learning to this domain. I'm interested in using remote sensing data to explain and tackle social issues.
  Further, I use a variety of statistical methods as time-series analysis in combination with different types of data to examine social phenomenas as e.g. poverty and environmental concern.
  As a data scientist I'm responsible for business analytics, user-segmentation analysis with unsupervised ML, and the development of features like a chatbot and a content enhancer using LLMs and
  prompt engineering.
  <br><br>

  <a href="https://www.linkedin.com/in/sebastian-bahr-61b58b197/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
